services:
  - type: web
    name: e-commerce_admin_webapp
    env: node
    rootDir: backend_engr
    buildCommand: |
      cd ../admin && npm install && npm run build
      cd ../engr && npm install && npm run build
    startCommand:  npm start
