services:
  - type: web
    name: backend_engr
    env: node
    buildCommand: |
      cd backend_engr && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://oluferonmijoshua:giF4BZ99DIiDogca@cluster0.11f1d.mongodb.net/e-commerce"
